name: "openpack-keypoint"
volume:
  rootdir: ${datarootdir}/datasets/openpack/
modality:
  keypoint:
    type: "mmpose-hrnet-mmdet/cleaned"
    num_vertex: 17
    format: "2D"
    frame_rate: 15 # Hz
split:
  train:
    - [102, 100]
    - [102, 200]
    - [102, 300]
  val:
    - [102, 400]
  test:
    - [102, 500]
  submission:
    - [102, 500]
num_classes: 10
