name: "openpack-acc"
volume:
  rootdir: ${datarootdir}/datasets/openpack/
modality:
  imu:
    nodes:
      - "atr01"
      - "atr02"
    use_acc: true
    use_gyro: false
    use_quat: false
split:
  train:
    - [102, 100]
    - [102, 200]
    - [102, 300]
  val:
    - [102, 400]
  test:
    - [102, 500]
  submission:
    - [102, 500]
num_classes: 10

